const stores =  [
    // { store: 'SATURN', url: 'https://www.saturn.de/de/product/_sony-playstation%C2%AE5-2661938.html', mainContainer: '#root', text: '#root > div.indexstyled__StyledAppWrapper-sc-1hu9cx8-0.hpmRoo > div.ProductDetailPagestyled__StyledPdpWrapper-sc-6keh57-1.jyghAf > div:nth-child(1) > div > div.Cellstyled__StyledCell-sc-1wk5bje-0.dNrMWM.ProductDetailPagestyled__StyledPdpDetailCell-sc-6keh57-5.kEhyWZ > div > div > div:nth-child(3) > div > span' },
    // { store: 'MEDIA MARKT', url:' https://www.mediamarkt.de/de/product/_sony-playstation%C2%AE5-2661938.html', mainContainer: '#root', text: '#root > div.indexstyled__StyledAppWrapper-sc-1hu9cx8-0.fwiTjF > div.ProductDetailPagestyled__StyledPdpWrapper-sc-6keh57-1.jyghAf > div:nth-child(1) > div > div.Cellstyled__StyledCell-sc-1wk5bje-0.dNrMWM.ProductDetailPagestyled__StyledPdpDetailCell-sc-6keh57-5.kEhyWZ > div > div > div:nth-child(3) > div > span'},
    { store: 'AMAZON', url: 'https://www.amazon.de/Sony-Interactive-Entertainment-PlayStation-5/dp/B08H93ZRK9/ref=sr_1_2?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=ps5&qid=1630790914&sr=8-2', mainContainer: '#dp-container', text: '#availability > span'},
    { store: 'EXPERT', url: 'https://ps5.expert.de/Themenwelten/Sony-PS5.html', mainContainer: 'body', text: 'body > div.pageWrapper.isChrome.isBlink > div > div > div.widget.widget-Root.widget-Root---1218fc06-b408-4a36-ab75-b71329096ee8.widget-Root---view-root.widget-Root-subContent.padding-xs-bottom-30 > div.widget.widget-Container.widget-Container---size-default.widget-Container---d6bc69a1-61a0-42db-8076-704fa9180dd7.widget-Container---view-container.widget-Container---preset-default > div > div.widget.widget-Container.widget-Container---size-default.widget-Container---786fb040-1b66-4d99-9abc-c717f99285bd.widget-Container---view-container.widget-Container---preset-default.margin-xs-bottom-30 > div > div > p > span'},
    { store: 'EURONICS', url: 'https://www.euronics.de/spiele-und-konsolen-film-und-musik/spiele-und-konsolen/playstation-5/spielekonsole/playstation-5-konsole-4061856837826', mainContainer: 'body > div > section', text: 'body > div > section > div > div > div > div > div > div > div > div > div.alert--content > span'},
    { store: 'MEDIMAX', url: 'https://www.medimax.de/ps5-reservierung-info', mainContainer: 'body', text: '#main-section > div.content-section > main > div:nth-child(2) > p:nth-child(7) > strong > span'},
    { store: 'OTTO', url: 'https://www.otto.de/technik/gaming/playstation/ps5/', mainContainer: 'body', text: '#san_privatePageContent > div.sanContentArea > div:nth-child(1) > div.promo-module-container > div:nth-child(2) > div' },
    { store: 'ALTERNATE', url: 'https://www.alternate.de/Sony-Interactive-Entertainment/PlayStation-5-Spielkonsole/html/product/1651220', mainContainer: 'body', text: '#product-top-right > div:nth-child(4) > div > div'},
    { store: 'MUELLER', url: 'https://www.mueller.de/multi-media/playstation-5/', mainContainer: 'body', text: '#page > main > div > div.mu-column-layout__content > div > div:nth-child(3) > div > div > h2'}
];

module.exports = stores;